apiVersion: v1
kind: Service
metadata:
  name: maintainerd
  labels:
    app: maintainerd
spec:
  selector:
    app: maintainerd
  ports:
    - name: http
      port: 2525
      targetPort: 2525
      protocol: TCP
  type: ClusterIP

